spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ayush
    url: jdbc:h2:mem:plandb
    username: ayush
  jpa:
    hibernate:
      ddl-auto: update

planapi:
  messages:
    planSaveSucc: Plan Saved Successfully
    planSaveFail: Plan Save Failed
    planUpdateSucc: Plan Updated Successfully
    planUpdateFail: Plan Update Failed
    planDeleteSucc: Plan Deleted Successfully
    planDeleteFail: Plan Delete Failed
    planStatusChange: Plan Status Changed Successfully
    planStatusChangeFail: Plan Status Change Failed
    